apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - ../../base
  - namespace.yaml
images:
  - name: kubeflow/training-operator
    digest: "sha256:f34aa502fc9435b3fc09c75a2ab8813b2d15d3d270db8651f35e64a464a0a77e"
